'use client'

import { useState, useEffect, useCallback } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import {
  X, Loader2, TrendingUp, TrendingDown, ChevronRight, ChevronDown,
  AlertTriangle, FileText, Package, Receipt, Info,
} from 'lucide-react'
import { useAppStore } from '@/store/app-store'
import { formatCurrency } from '@/lib/utils'
import { explainProfitLoss, type ProfitLossExplanation } from '@/lib/profit-loss-explainer'
import type { DashboardRange } from '@/lib/date-ranges'

/**
 * §P16-STEP3.8.1-DRILLDOWN: Profit/Loss drill-down bottom sheet.
 *
 * Architecture (Level 2 + Level 3):
 *   - Level 2: Period summary + "Why?" explanation + metric rows (tappable)
 *   - Level 3: Inline expansion of metric rows → underlying records
 *
 * §CORRECTION-2 (Minimize API surface): Fetches directly from
 * /api/dashboard/breakdown — self-contained, no dependency on extended
 * /api/invoices or /api/transactions GET.
 *
 * §CORRECTION-4 (Server-derived): The client sends ONLY range + customStart
 * + customEnd + bucketIndex. The server derives bucketStart/bucketEnd.
 *
 * §CORRECTION-6 (Traceability): Full hierarchy — every displayed number
 * traces back to underlying invoices / products / transactions.
 *
 * §CORRECTION-1 (Never inventory purchase as loss cause): The "Why?"
 * explanation is generated by the pure rule-based explainer in
 * src/lib/profit-loss-explainer.ts. NEVER mentions inventory purchase.
 *
 * §MOBILE: Bottom sheet pattern, min 44px touch targets, no horizontal
 * overflow, preserves dashboard range context.
 */

interface DrilldownBucket {
  index: number
  fullDate: string
}

interface ProfitLossDrilldownSheetProps {
  open: boolean
  onClose: () => void
  bucket: DrilldownBucket | null
  range: DashboardRange
  customStart: string
  customEnd: string
  currency: string
}

// ─── Server response types (mirror /api/dashboard/breakdown response shape) ───
interface BreakdownResponse {
  period: {
    label: string
    fullLabel: string
    startISO: string
    endISO: string
    bucketType: string
  }
  summary: {
    netRevenue: number
    cogs: number
    grossProfit: number
    operatingExpense: number
    legacyOpEx: number
    netProfit: number
  }
  breakdown: {
    revenueSources: Array<{
      invoiceId: string
      invoiceNumber: string
      partyId: string | null
      partyName: string | null
      netRevenueContribution: number
      grandTotal: number
      date: string
    }>
    cogsSources: Array<{
      productId: string
      productName: string
      quantitySold: number
      historicalCostPerUnit: number | null
      fallbackCostPerUnit: number | null
      totalCogsContribution: number
      invoiceId: string
      invoiceNumber: string
      isApproximate: boolean
    }>
    expenseSources: {
      authoritative: Array<{
        transactionId: string
        category: string
        description: string
        amount: number
        date: string
        isAuthoritative: true
      }>
      legacy: Array<{
        transactionId: string
        category: string
        description: string
        amount: number
        date: string
        isAuthoritative: false
        classificationNote: string
      }>
    }
  }
  cogsAccuracy: {
    snapshotItems: number
    fallbackItems: number
    isApproximate: boolean
  }
}

type ExpandedMetric = 'revenue' | 'cogs' | 'grossProfit' | 'operatingExpense' | 'legacyOpEx' | 'netProfit' | null

export function ProfitLossDrilldownSheet({
  open, onClose, bucket, range, customStart, customEnd, currency,
}: ProfitLossDrilldownSheetProps) {
  const { setSelectedInvoiceId, setFloatingInvoiceOpen, setSelectedProductId } = useAppStore()
  const [data, setData] = useState<BreakdownResponse | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [expanded, setExpanded] = useState<ExpandedMetric>(null)

  // §FETCH: Load breakdown data when the sheet opens with a bucket.
  // Client sends ONLY range + customStart + customEnd + bucketIndex.
  // Server derives ALL bucket boundaries.
  const loadBreakdown = useCallback(async () => {
    if (!bucket) return
    setLoading(true)
    setError(null)
    setExpanded(null)
    try {
      const params = new URLSearchParams({
        range,
        bucketIndex: String(bucket.index),
      })
      if (range === 'custom' && customStart && customEnd) {
        params.set('startDate', customStart)
        params.set('endDate', customEnd)
      }
      const res = await fetch(`/api/dashboard/breakdown?${params.toString()}`)
      const json = await res.json()
      if (!res.ok) {
        setError(json.error || 'Failed to load breakdown')
        setData(null)
      } else {
        setData(json)
      }
    } catch {
      setError('Network error')
      setData(null)
    } finally {
      setLoading(false)
    }
  }, [bucket, range, customStart, customEnd])

  useEffect(() => {
    if (open && bucket) {
      loadBreakdown()
    } else if (!open) {
      setData(null)
      setError(null)
      setExpanded(null)
    }
  }, [open, bucket, loadBreakdown])

  // §NAVIGATION: Reuse existing detail-page navigation hooks.
  // Invoice → FloatingInvoiceModal (existing)
  // Product → ProductProfile via InventoryView (existing)
  const handleInvoiceTap = (invoiceId: string) => {
    setSelectedInvoiceId(invoiceId)
    setFloatingInvoiceOpen(true)
    onClose()
  }
  const handleProductTap = (productId: string) => {
    setSelectedProductId(productId)
    onClose()
  }

  const toggle = (metric: ExpandedMetric) => {
    setExpanded(prev => prev === metric ? null : metric)
  }

  // §EXPLAINER: Generate the "Why?" explanation from server-authoritative summary.
  // Pure function — no AI, no LLM, no API call. NEVER mentions inventory purchase.
  const explanation: ProfitLossExplanation | null = data
    ? explainProfitLoss({
        netRevenue: data.summary.netRevenue,
        cogs: data.summary.cogs,
        grossProfit: data.summary.grossProfit,
        operatingExpense: data.summary.operatingExpense,
        legacyOpEx: data.summary.legacyOpEx,
        netProfit: data.summary.netProfit,
      })
    : null

  const isLoss = data ? data.summary.netProfit < 0 : false

  return (
    <AnimatePresence>
      {open && bucket && (
        <>
          {/* Backdrop */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
            className="fixed inset-0 z-[90] bg-black/40 backdrop-blur-[2px]"
          />
          {/* Sheet */}
          <motion.div
            initial={{ y: '100%' }}
            animate={{ y: 0 }}
            exit={{ y: '100%' }}
            transition={{ type: 'spring', stiffness: 400, damping: 32 }}
            className="fixed bottom-0 inset-x-0 z-[100] bg-card rounded-t-3xl border-t border-border max-w-2xl mx-auto max-h-[90vh] flex flex-col"
          >
            {/* Header */}
            <div className="flex items-center justify-between p-4 pb-2 border-b border-border shrink-0">
              <div className="min-w-0 flex-1">
                <h3 className="text-sm font-semibold flex items-center gap-1.5">
                  <TrendingUp className="w-4 h-4 shrink-0" />
                  <span className="truncate">P&L Breakdown</span>
                </h3>
                {data && (
                  <p className="text-xs text-muted-foreground mt-0.5 truncate">
                    {data.period.fullLabel}
                  </p>
                )}
              </div>
              <button
                onClick={onClose}
                className="w-9 h-9 rounded-full hover:bg-muted flex items-center justify-center shrink-0 ml-2"
                aria-label="Close"
              >
                <X className="w-4 h-4" />
              </button>
            </div>

            {/* Body — scrollable */}
            <div className="overflow-y-auto overscroll-contain p-4 space-y-3 flex-1">
              {loading && (
                <div className="flex items-center justify-center py-8">
                  <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
                </div>
              )}

              {error && (
                <div className="text-center py-8 text-destructive text-sm">
                  <AlertTriangle className="w-6 h-6 mx-auto mb-2" />
                  {error}
                </div>
              )}

              {data && explanation && !loading && !error && (
                <>
                  {/* §WHY — Rule-based explanation (Correction #1: never inventory purchase) */}
                  <div className={`rounded-xl p-3 border ${isLoss ? 'bg-red-50 dark:bg-red-950/20 border-red-200 dark:border-red-800' : 'bg-emerald-50 dark:bg-emerald-950/20 border-emerald-200 dark:border-emerald-800'}`}>
                    <p className={`text-xs font-semibold mb-1 ${isLoss ? 'text-red-700 dark:text-red-300' : 'text-emerald-700 dark:text-emerald-300'}`}>
                      {isLoss ? '📉 Why did I make a loss?' : '📈 Why did I make a profit?'}
                    </p>
                    <p className="text-xs text-foreground leading-relaxed">
                      {explanation.primaryReason}
                    </p>
                    {/* Contributing factors */}
                    <div className="mt-2 space-y-0.5">
                      {explanation.contributingFactors.map(f => (
                        <div key={f.label} className="flex items-center justify-between text-[11px]">
                          <span className="text-muted-foreground">{f.label}</span>
                          <span className={f.impact === 'positive' ? 'text-emerald-600 dark:text-emerald-400 font-medium' : f.impact === 'negative' ? 'text-red-600 dark:text-red-400 font-medium' : 'text-muted-foreground font-medium'}>
                            {formatCurrency(f.value, currency)}
                          </span>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* §METRIC-ROWS: Each P&L line is tappable to drill down (Level 3) */}
                  <MetricRow
                    label="Net Profit / Loss"
                    value={data.summary.netProfit}
                    currency={currency}
                    isLoss={isLoss}
                    isBold
                    icon={isLoss ? <TrendingDown className="w-4 h-4" /> : <TrendingUp className="w-4 h-4" />}
                    expanded={expanded === 'netProfit'}
                    onToggle={() => toggle('netProfit')}
                  >
                    {/* Net Profit is the formula result — show its components */}
                    <div className="space-y-1 text-xs text-muted-foreground px-1">
                      <p>= Net Revenue − COGS − Operating Expense</p>
                      <p>= {formatCurrency(data.summary.netRevenue, currency)} − {formatCurrency(data.summary.cogs, currency)} − {formatCurrency(data.summary.operatingExpense, currency)}</p>
                      <p className="font-semibold text-foreground mt-1">= {formatCurrency(data.summary.netProfit, currency)}</p>
                    </div>
                  </MetricRow>

                  <MetricRow
                    label="Net Revenue"
                    sublabel="tax-exclusive (subtotal − discount)"
                    value={data.summary.netRevenue}
                    currency={currency}
                    icon={<TrendingUp className="w-4 h-4" />}
                    expanded={expanded === 'revenue'}
                    onToggle={() => toggle('revenue')}
                  >
                    {/* §LEVEL-3: Revenue → invoice list → FloatingInvoiceModal */}
                    <div className="space-y-1">
                      {data.breakdown.revenueSources.length === 0 ? (
                        <p className="text-xs text-muted-foreground px-1 py-1">No sales in this period.</p>
                      ) : (
                        data.breakdown.revenueSources.map(src => (
                          <button
                            key={src.invoiceId}
                            onClick={() => handleInvoiceTap(src.invoiceId)}
                            className="w-full flex items-center justify-between gap-2 p-2 rounded-lg hover:bg-muted text-left min-h-[44px]"
                          >
                            <div className="min-w-0 flex-1">
                              <p className="text-xs font-medium truncate">{src.invoiceNumber}</p>
                              <p className="text-[10px] text-muted-foreground truncate">
                                {src.partyName || 'Walk-in'} · {new Date(src.date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' })}
                              </p>
                            </div>
                            <div className="flex items-center gap-1 shrink-0">
                              <span className="text-xs font-semibold text-emerald-600 dark:text-emerald-400">
                                {formatCurrency(src.netRevenueContribution, currency)}
                              </span>
                              <ChevronRight className="w-3 h-3 text-muted-foreground" />
                            </div>
                          </button>
                        ))
                      )}
                    </div>
                  </MetricRow>

                  <MetricRow
                    label="COGS"
                    sublabel={data.cogsAccuracy.isApproximate ? `${data.cogsAccuracy.fallbackItems} of ${data.cogsAccuracy.snapshotItems + data.cogsAccuracy.fallbackItems} items use current cost (no historical snapshot)` : 'historical cost (snapshot captured at sale)'}
                    value={data.summary.cogs}
                    currency={currency}
                    icon={<Package className="w-4 h-4" />}
                    expanded={expanded === 'cogs'}
                    onToggle={() => toggle('cogs')}
                  >
                    {/* §LEVEL-3: COGS → product-level breakdown → ProductProfile / invoice */}
                    <div className="space-y-1">
                      {data.breakdown.cogsSources.length === 0 ? (
                        <p className="text-xs text-muted-foreground px-1 py-1">No product costs in this period.</p>
                      ) : (
                        <>
                          {data.breakdown.cogsSources.map((src, i) => (
                            <div key={`${src.productId}-${i}`} className="p-2 rounded-lg bg-muted/50">
                              <button
                                onClick={() => handleProductTap(src.productId)}
                                className="w-full flex items-center justify-between gap-2 text-left min-h-[44px]"
                              >
                                <div className="min-w-0 flex-1">
                                  <p className="text-xs font-medium truncate">{src.productName}</p>
                                  <p className="text-[10px] text-muted-foreground">
                                    Qty: {src.quantitySold} · {src.invoiceNumber}
                                  </p>
                                </div>
                                <div className="flex items-center gap-1 shrink-0">
                                  <span className="text-xs font-semibold text-amber-600 dark:text-amber-400">
                                    {formatCurrency(src.totalCogsContribution, currency)}
                                  </span>
                                  <ChevronRight className="w-3 h-3 text-muted-foreground" />
                                </div>
                              </button>
                              <div className="mt-1 text-[10px] text-muted-foreground flex items-center gap-1">
                                <Info className="w-2.5 h-2.5 shrink-0" />
                                {src.isApproximate ? (
                                  <span>
                                    Cost/unit: {formatCurrency(src.fallbackCostPerUnit ?? 0, currency)}{' '}
                                    <span className="text-amber-600 dark:text-amber-400">(current — no historical snapshot)</span>
                                  </span>
                                ) : (
                                  <span>Cost/unit: {formatCurrency(src.historicalCostPerUnit ?? 0, currency)} (historical snapshot)</span>
                                )}
                              </div>
                            </div>
                          ))}
                          {data.cogsAccuracy.isApproximate && (
                            <div className="mt-2 p-2 rounded-lg bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800">
                              <p className="text-[10px] text-amber-700 dark:text-amber-300 flex items-start gap-1">
                                <AlertTriangle className="w-3 h-3 shrink-0 mt-0.5" />
                                <span>COGS is approximate — {data.cogsAccuracy.fallbackItems} item(s) have no historical cost snapshot and use the current product purchase price.</span>
                              </p>
                            </div>
                          )}
                        </>
                      )}
                    </div>
                  </MetricRow>

                  <MetricRow
                    label="Gross Profit"
                    sublabel="Net Revenue − COGS"
                    value={data.summary.grossProfit}
                    currency={currency}
                    icon={<TrendingUp className="w-4 h-4" />}
                    expanded={expanded === 'grossProfit'}
                    onToggle={() => toggle('grossProfit')}
                  >
                    <div className="space-y-1 text-xs px-1">
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">Net Revenue</span>
                        <span className="text-emerald-600 dark:text-emerald-400">{formatCurrency(data.summary.netRevenue, currency)}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-muted-foreground">− COGS</span>
                        <span className="text-amber-600 dark:text-amber-400">{formatCurrency(data.summary.cogs, currency)}</span>
                      </div>
                      <div className="flex justify-between border-t border-border mt-1 pt-1">
                        <span className="font-medium">= Gross Profit</span>
                        <span className="font-semibold">{formatCurrency(data.summary.grossProfit, currency)}</span>
                      </div>
                    </div>
                  </MetricRow>

                  <MetricRow
                    label="Operating Expense"
                    sublabel="authoritative (subtype=operating_expense)"
                    value={data.summary.operatingExpense}
                    currency={currency}
                    icon={<Receipt className="w-4 h-4" />}
                    expanded={expanded === 'operatingExpense'}
                    onToggle={() => toggle('operatingExpense')}
                  >
                    {/* §LEVEL-3: Operating Expense → authoritative transaction list */}
                    <div className="space-y-1">
                      {data.breakdown.expenseSources.authoritative.length === 0 ? (
                        <p className="text-xs text-muted-foreground px-1 py-1">No authoritative operating expenses in this period.</p>
                      ) : (
                        data.breakdown.expenseSources.authoritative.map(src => (
                          <div key={src.transactionId} className="p-2 rounded-lg bg-muted/50">
                            <div className="flex items-center justify-between gap-2">
                              <div className="min-w-0 flex-1">
                                <p className="text-xs font-medium truncate">{src.description || src.category}</p>
                                <p className="text-[10px] text-muted-foreground">{src.category} · {new Date(src.date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' })}</p>
                              </div>
                              <span className="text-xs font-semibold text-red-600 dark:text-red-400 shrink-0">
                                {formatCurrency(src.amount, currency)}
                              </span>
                            </div>
                          </div>
                        ))
                      )}
                    </div>
                  </MetricRow>

                  {/* §LEGACY-OPEX: SEPARATE — NEVER merged into Operating Expense */}
                  {data.summary.legacyOpEx > 0 && (
                    <MetricRow
                      label="Unclassified (legacy)"
                      sublabel="pre-Step 3.1 — NOT included in authoritative Net Profit"
                      value={data.summary.legacyOpEx}
                      currency={currency}
                      icon={<AlertTriangle className="w-4 h-4" />}
                      expanded={expanded === 'legacyOpEx'}
                      onToggle={() => toggle('legacyOpEx')}
                      isLegacy
                    >
                      {/* §LEVEL-3: Legacy → legacy transaction list (always isAuthoritative=false) */}
                      <div className="space-y-1">
                        {data.breakdown.expenseSources.legacy.map(src => (
                          <div key={src.transactionId} className="p-2 rounded-lg bg-muted/50">
                            <div className="flex items-center justify-between gap-2">
                              <div className="min-w-0 flex-1">
                                <p className="text-xs font-medium truncate">{src.description || src.category}</p>
                                <p className="text-[10px] text-muted-foreground">{src.category} · {new Date(src.date).toLocaleDateString('en-IN', { day: '2-digit', month: 'short' })}</p>
                                <p className="text-[10px] text-amber-600 dark:text-amber-400 mt-0.5">{src.classificationNote}</p>
                              </div>
                              <span className="text-xs font-semibold text-muted-foreground shrink-0">
                                {formatCurrency(src.amount, currency)}
                              </span>
                            </div>
                          </div>
                        ))}
                      </div>
                    </MetricRow>
                  )}
                </>
              )}
            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  )
}

// ─── MetricRow: tappable P&L line item that expands to show breakdown ──────

interface MetricRowProps {
  label: string
  sublabel?: string
  value: number
  currency: string
  icon: React.ReactNode
  expanded: boolean
  onToggle: () => void
  isBold?: boolean
  isLegacy?: boolean
  isLoss?: boolean
  children?: React.ReactNode
}

function MetricRow({ label, sublabel, value, currency, icon, expanded, onToggle, isBold, isLegacy, isLoss, children }: MetricRowProps) {
  const valueColor = isLegacy
    ? 'text-muted-foreground'
    : isLoss === true
    ? 'text-red-600 dark:text-red-400'
    : label === 'COGS' || label === 'Operating Expense'
    ? 'text-amber-600 dark:text-amber-400'
    : label === 'Net Revenue' || label === 'Gross Profit'
    ? 'text-emerald-600 dark:text-emerald-400'
    : isLoss === false
    ? 'text-emerald-600 dark:text-emerald-400'
    : 'text-foreground'

  return (
    <div className={`rounded-xl border ${isLegacy ? 'border-amber-200 dark:border-amber-800 bg-amber-50/50 dark:bg-amber-950/10' : 'border-border bg-card'}`}>
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between gap-2 p-3 text-left min-h-[44px]"
        aria-expanded={expanded}
      >
        <div className="flex items-center gap-2 min-w-0 flex-1">
          <span className={`${isLegacy ? 'text-amber-600 dark:text-amber-400' : 'text-muted-foreground'} shrink-0`}>{icon}</span>
          <div className="min-w-0">
            <p className={`text-xs ${isBold ? 'font-bold' : 'font-medium'} truncate ${isLegacy ? 'text-amber-700 dark:text-amber-300' : ''}`}>
              {label}
            </p>
            {sublabel && (
              <p className="text-[10px] text-muted-foreground truncate">{sublabel}</p>
            )}
          </div>
        </div>
        <div className="flex items-center gap-1 shrink-0">
          <span className={`text-sm ${isBold ? 'font-bold' : 'font-semibold'} ${valueColor}`}>
            {formatCurrency(value, currency)}
          </span>
          {children && (
            <ChevronDown className={`w-4 h-4 text-muted-foreground transition-transform ${expanded ? 'rotate-180' : ''}`} />
          )}
        </div>
      </button>
      {expanded && children && (
        <div className="px-1 pb-2 border-t border-border/50 pt-2">
          {children}
        </div>
      )}
    </div>
  )
}
