import { NextRequest, NextResponse } from 'next/server'
import { db, getCurrentBusiness } from '@/lib/db'
import { apiError } from '@/lib/api-error'
import {
  computeRangeBounds,
  computeBuckets,
  type DashboardRange,
  type Bucket,
} from '@/lib/date-ranges'

/**
 * §P16-STEP3.8.1-DASHBOARD-DRILLDOWN: GET /api/dashboard/breakdown
 *
 * Self-contained drill-down endpoint for the Profit & Loss chart.
 * Given a dashboard range + bucketIndex, returns the server-derived
 * bucket boundaries + every underlying record (invoices, invoice items
 * with products, expense transactions) that produced the P&L totals for
 * that bucket.
 *
 * §CORRECTION-2 (Minimize API Surface): This endpoint is SELF-CONTAINED.
 * It does NOT depend on extensions to /api/invoices or /api/transactions
 * GET handlers. All queries are performed directly here, business-scoped.
 *
 * §CORRECTION-4 (Server-Derived): The client sends ONLY:
 *   - range (validated against DASHBOARD_RANGES whitelist)
 *   - startDate / endDate (required only when range='custom')
 *   - bucketIndex (integer, validated < server-computed bucketCount)
 *
 * The server derives rangeStart, rangeEnd, bucketType, bucketCount,
 * bucketStart, bucketEnd — NEVER trusts client-provided boundaries.
 *
 * §CORRECTION-5 (Accounting Semantics — verbatim):
 *   - Total Sales      = SUM(invoice.grandTotal)              — tax-INCLUSIVE
 *   - Net Revenue      = SUM(invoice.subtotal - discountAmount) — tax-EXCLUSIVE
 *   - COGS             = SUM(item.quantity × (purchasePriceSnapshot
 *                                           ?? product.purchasePrice
 *                                           ?? 0))             — historical cost
 *   - Gross Profit     = Net Revenue - COGS
 *   - Operating Expense= AUTHORITATIVE ONLY (subtype='operating_expense')
 *   - Legacy/unclassified = NULL-subtype + type IN (debit,expense) + invoiceId IS NULL
 *   - Net Profit       = Gross Profit - authoritative Operating Expense
 *
 * §CORRECTION-1 (Never inventory purchase as loss cause):
 *   Inventory purchases are an ASSET MOVEMENT (cash → inventory), NOT a
 *   P&L expense. COGS is recognized only when inventory is SOLD. The
 *   insights generated by this endpoint NEVER describe inventory purchase
 *   as a P&L loss cause. The explanation logic lives in
 *   `src/lib/profit-loss-explainer.ts` (Phase 2).
 *
 * §ACCOUNTING-FREEZE: This endpoint is READ-ONLY. It does NOT create,
 * update, or delete any records. It does NOT modify any accounting
 * formulas, classifications, or write paths. It RE-COMPUTES the same
 * values (using the same formulas) as the dashboard route, for display.
 *
 * §TENANT-ISOLATION: Every query is scoped by `business.id` from the
 * authenticated session. Business A can NEVER read Business B's records.
 */
export const maxDuration = 20

// §REVENUE-SCOPE: Same as dashboard route — only sales/retail invoices
// contribute to revenue/COGS. Purchase invoices (asset movement) and
// voided invoices are EXCLUDED.
const REVENUE_INVOICE_TYPES = ['sales', 'retail'] as const

// §EXPENSE-TYPES: Same as dashboard route's EXPENSE_TYPES. Used for
// legacy NULL-subtype classification. 'purchase' is intentionally NOT
// included (dead type, aligned with Reports).
const EXPENSE_TYPES = ['debit', 'expense'] as const

// §BUCKET-CAP: Prevent unbounded query results. A single bucket (1 day,
// 1 week, 1 month) should not have more than these caps. If it does,
// the user has bigger data-scale issues than drill-down UX.
const MAX_INVOICES_PER_BUCKET = 200
const MAX_TRANSACTIONS_PER_BUCKET = 100

// §DECIMAL-FIX: Prisma Decimal fields return as string. Convert to Number.
const num = (v: any): number => Number(v) || 0

export async function GET(req: NextRequest) {
  try {
    const business = await getCurrentBusiness()
    if (!business) {
      return NextResponse.json({ error: 'Not authenticated' }, { status: 401 })
    }

    const { searchParams } = new URL(req.url)
    const rangeParam = searchParams.get('range') as DashboardRange | null
    const startDate = searchParams.get('startDate')
    const endDate = searchParams.get('endDate')
    const bucketIndexRaw = searchParams.get('bucketIndex')

    // ─── §VALIDATE-RANGE ────────────────────────────────────────────────
    const VALID_RANGES: DashboardRange[] = [
      '1d', 'yesterday', '2d', '3d', '5d', '7d',
      '1m', '3m', '6m', '1y', 'custom',
    ]
    if (!rangeParam || !VALID_RANGES.includes(rangeParam)) {
      return NextResponse.json({ error: 'Invalid range' }, { status: 400 })
    }
    if (rangeParam === 'custom' && (!startDate || !endDate)) {
      return NextResponse.json(
        { error: 'Custom range requires startDate and endDate' },
        { status: 400 },
      )
    }

    // ─── §VALIDATE-BUCKET-INDEX ────────────────────────────────────────
    if (bucketIndexRaw == null) {
      return NextResponse.json({ error: 'Invalid bucketIndex' }, { status: 400 })
    }
    const bucketIndex = Number(bucketIndexRaw)
    if (!Number.isInteger(bucketIndex) || bucketIndex < 0) {
      return NextResponse.json({ error: 'Invalid bucketIndex' }, { status: 400 })
    }

    // ─── §SERVER-DERIVED-RANGE-BOUNDARIES ─────────────────────────────
    // §CORRECTION-4: Server derives rangeStart/rangeEnd via the SAME
    // function the dashboard uses. Client NEVER provides these.
    const bounds = computeRangeBounds(rangeParam, startDate, endDate)
    if (!bounds) {
      return NextResponse.json(
        { error: 'Invalid range: could not compute boundaries' },
        { status: 400 },
      )
    }
    const rangeStart: Date = bounds.start
    const rangeEnd: Date = bounds.end

    // ─── §SERVER-DERIVED-BUCKET-CONFIG ─────────────────────────────────
    // §MIRROR-DASHBOARD-BUCKETING: This logic is a faithful copy of the
    // bucket-selection logic in /api/dashboard/route.ts lines 62-93.
    // It MUST stay in sync. (Not extracted to a shared helper to avoid
    // touching the frozen dashboard route — see §ACCOUNTING-FREEZE.)
    const rangeDays = Math.ceil((rangeEnd.getTime() - rangeStart.getTime()) / 86400000)
    let bucketType: 'hour' | 'day' | 'week' | 'month' = 'day'
    let bucketCount = 7
    if (rangeParam === '1d' || rangeParam === 'yesterday') {
      bucketType = 'hour'; bucketCount = 24
    } else if (rangeParam === '2d' || rangeParam === '3d' || rangeParam === '5d') {
      bucketType = 'day'; bucketCount = Math.max(2, rangeDays)
    } else if (rangeParam === '7d') {
      bucketType = 'day'; bucketCount = 7
    } else if (rangeParam === '1m') {
      bucketType = 'day'; bucketCount = 30
    } else if (rangeParam === '3m') {
      bucketType = 'week'; bucketCount = 13
    } else if (rangeParam === '6m') {
      bucketType = 'month'; bucketCount = 6
    } else if (rangeParam === '1y') {
      bucketType = 'month'; bucketCount = 12
    } else if (rangeParam === 'custom') {
      if (rangeDays <= 1) {
        bucketType = 'hour'; bucketCount = 24
      } else if (rangeDays <= 7) {
        bucketType = 'day'; bucketCount = rangeDays
      } else if (rangeDays <= 90) {
        bucketType = 'week'; bucketCount = Math.ceil(rangeDays / 7)
      } else if (rangeDays <= 720) {
        bucketType = 'month'; bucketCount = Math.ceil(rangeDays / 30)
      } else {
        bucketType = 'month'; bucketCount = 24
      }
    }

    // ─── §VALIDATE-BUCKET-INDEX-AGAINST-COUNT ─────────────────────────
    if (bucketIndex >= bucketCount) {
      return NextResponse.json(
        { error: 'bucketIndex out of range' },
        { status: 400 },
      )
    }

    // ─── §SERVER-DERIVED-BUCKET-BOUNDARIES ────────────────────────────
    // §CORRECTION-4: Server picks the bucket from the computed array.
    // Client NEVER provides bucketStart/bucketEnd.
    const buckets: Bucket[] = computeBuckets(rangeStart, rangeEnd, bucketType, bucketCount)
    const bucket: Bucket = buckets[bucketIndex]
    const bucketStart: Date = bucket.start
    const bucketEnd: Date = bucket.end

    // ─── §SELF-CONTAINED-QUERIES ──────────────────────────────────────
    // §CORRECTION-2: All queries performed directly here. No dependency
    // on /api/invoices or /api/transactions GET extensions.
    //
    // 1. Invoices in the bucket (with items + party + product relation)
    //    — scoped by businessId, type IN (sales, retail), status != void
    //    — same voidExclude + revenue-scope as dashboard route.
    // 2. Expense transactions in the bucket — scoped by businessId,
    //    filtered to operating_expense OR legacy unclassified.
    //
    // §PARALLEL: Both queries run in a single Promise.all for efficiency.
    const [bucketInvoices, bucketExpenseTxns] = await Promise.all([
      db.invoice.findMany({
        where: {
          businessId: business.id,
          type: { in: [...REVENUE_INVOICE_TYPES] },
          status: { not: 'void' },
          createdAt: { gte: bucketStart, lte: bucketEnd },
        },
        include: {
          party: { select: { id: true, name: true } },
          items: {
            include: {
              product: {
                select: {
                  id: true,
                  name: true,
                  purchasePrice: true,
                },
              },
            },
          },
        },
        orderBy: { createdAt: 'desc' },
        take: MAX_INVOICES_PER_BUCKET,
      }),
      db.transaction.findMany({
        where: {
          businessId: business.id,
          createdAt: { gte: bucketStart, lte: bucketEnd },
          // §OPEX-FILTER: Only expense-related transactions.
          //   - subtype='operating_expense' (authoritative)
          //   - OR legacy: subtype IS NULL + type IN (debit, expense) + invoiceId IS NULL
          //   (matches dashboard route's legacyOpEx classification exactly)
          OR: [
            { transactionSubtype: 'operating_expense' },
            {
              transactionSubtype: null,
              type: { in: [...EXPENSE_TYPES] },
              invoiceId: null,
            },
          ],
        },
        orderBy: { createdAt: 'desc' },
        take: MAX_TRANSACTIONS_PER_BUCKET,
      }),
    ])

    // ─── §BUILD-BREAKDOWN ─────────────────────────────────────────────
    //
    // §ACCOUNTING-SEMANTICS (verbatim from approved plan §5):
    //   - Net Revenue      = SUM(invoice.subtotal - invoice.discountAmount)
    //   - COGS             = SUM(item.quantity × (snapshot ?? product.purchasePrice ?? 0))
    //   - Gross Profit     = Net Revenue - COGS
    //   - Operating Expense= AUTHORITATIVE ONLY (subtype='operating_expense')
    //   - Legacy OpEx      = NULL-subtype + type debit/expense + invoiceId IS NULL
    //   - Net Profit       = Gross Profit - authoritative Operating Expense
    //
    // These are the SAME formulas the dashboard route uses (lines 339-404).
    // No accounting write-logic is touched. READ-ONLY recomputation.

    // §REVENUE-SOURCES: One entry per invoice in the bucket.
    const revenueSources = bucketInvoices.map((inv) => {
      const subtotal = num(inv.subtotal)
      const discountAmount = num(inv.discountAmount)
      const netRevenueContribution = subtotal - discountAmount
      return {
        invoiceId: inv.id,
        invoiceNumber: inv.invoiceNumber,
        partyId: inv.partyId,
        partyName: inv.party?.name ?? null,
        // §NET-REVENUE-CONTRIBUTION: subtotal - discountAmount for THIS invoice (tax-exclusive)
        netRevenueContribution,
        // §CONTEXT: grandTotal (tax-inclusive) for display context
        grandTotal: num(inv.grandTotal),
        date: inv.createdAt.toISOString(),
      }
    })

    // §COGS-SOURCES: One entry per invoice item (product-line) in the bucket.
    // Flattens bucketInvoices[].items[] into a single array.
    // Each entry captures the historical snapshot cost (if present) and
    // explicitly flags whether the current product.purchasePrice fallback
    // was used (isApproximate=true). NEVER silently presents fallback as historical.
    let snapshotItems = 0
    let fallbackItems = 0
    const cogsSources: Array<{
      productId: string
      productName: string
      quantitySold: number
      historicalCostPerUnit: number | null
      fallbackCostPerUnit: number | null
      totalCogsContribution: number
      invoiceId: string
      invoiceNumber: string
      isApproximate: boolean
    }> = []
    for (const inv of bucketInvoices) {
      for (const item of inv.items) {
        const quantitySold = item.quantity
        const snapshot = item.purchasePriceSnapshot != null ? num(item.purchasePriceSnapshot) : null
        const fallback = item.product ? num(item.product.purchasePrice) : null
        // §COST-PER-UNIT: Prefer historical snapshot; fall back to current
        // product.purchasePrice ONLY when snapshot is NULL.
        const costPerUnit = snapshot != null ? snapshot : (fallback ?? 0)
        const isApproximate = snapshot == null
        const totalCogsContribution = quantitySold * costPerUnit
        if (isApproximate) {
          fallbackItems++
        } else {
          snapshotItems++
        }
        // §SKIP-NULL-PRODUCT: If item has no productId (ad-hoc line item),
        // skip it from cogsSources (no product to attribute cost to). This
        // matches dashboard route behavior (costPerUnit=0 for null productId).
        if (!item.productId) continue
        cogsSources.push({
          productId: item.productId,
          productName: item.product?.name ?? item.name,
          quantitySold,
          historicalCostPerUnit: snapshot,
          fallbackCostPerUnit: fallback,
          totalCogsContribution,
          invoiceId: inv.id,
          invoiceNumber: inv.invoiceNumber,
          isApproximate,
        })
      }
    }

    // §OPERATING-EXPENSE-SOURCES: Split into authoritative + legacy.
    // §CORRECTION-6: NEVER merge legacy into authoritative. Each list
    // has its own isAuthoritative flag (always true / always false).
    const authoritativeExpenses = bucketExpenseTxns
      .filter((t) => t.transactionSubtype === 'operating_expense')
      .map((t) => ({
        transactionId: t.id,
        category: t.category ?? 'Uncategorized',
        description: t.description ?? '',
        amount: num(t.amount),
        date: t.createdAt.toISOString(),
        // §ALWAYS-TRUE: authoritative transactions are ALWAYS authoritative
        isAuthoritative: true as const,
      }))
    const legacyExpenses = bucketExpenseTxns
      .filter(
        (t) =>
          t.transactionSubtype == null &&
          EXPENSE_TYPES.includes(t.type as any) &&
          !t.invoiceId,
      )
      .map((t) => ({
        transactionId: t.id,
        category: t.category ?? 'Uncategorized',
        description: t.description ?? '',
        amount: num(t.amount),
        date: t.createdAt.toISOString(),
        // §ALWAYS-FALSE: legacy transactions are NEVER authoritative
        isAuthoritative: false as const,
        classificationNote:
          'Unclassified (pre-Step 3.1) — not included in authoritative Net Profit',
      }))

    // ─── §SUMMARY-TOTALS ───────────────────────────────────────────────
    // §RECOMPUTED: Server-authoritative. NEVER from client.
    const netRevenue = revenueSources.reduce(
      (s, r) => s + r.netRevenueContribution,
      0,
    )
    const cogs = cogsSources.reduce((s, c) => s + c.totalCogsContribution, 0)
    const grossProfit = netRevenue - cogs
    const operatingExpense = authoritativeExpenses.reduce((s, e) => s + e.amount, 0)
    const legacyOpEx = legacyExpenses.reduce((s, e) => s + e.amount, 0)
    // §NET-PROFIT: Gross Profit - AUTHORITATIVE Operating Expense.
    // Legacy OpEx is NOT subtracted (disclosed separately).
    // CAN BE NEGATIVE — the explainer handles this in Phase 2.
    const netProfit = grossProfit - operatingExpense

    // ─── §PERIOD-LABEL ─────────────────────────────────────────────────
    // §SERVER-DERIVED: The bucket label is generated server-side from
    // the bucket's start date. Uses IST timezone (Asia/Kolkata).
    const IST_TZ = 'Asia/Kolkata'
    let fullLabel: string
    try {
      if (bucketType === 'hour') {
        const endHour = new Date(bucketStart.getTime() + 60 * 60 * 1000)
        const dateStr = bucketStart.toLocaleDateString('en-US', {
          weekday: 'long', day: '2-digit', month: 'long', year: 'numeric', timeZone: IST_TZ,
        })
        const startTime = bucketStart.toLocaleTimeString('en-US', {
          hour: 'numeric', minute: '2-digit', hour12: true, timeZone: IST_TZ,
        })
        const endTime = endHour.toLocaleTimeString('en-US', {
          hour: 'numeric', minute: '2-digit', hour12: true, timeZone: IST_TZ,
        })
        fullLabel = `${dateStr}, ${startTime} – ${endTime}`
      } else if (bucketType === 'week') {
        const endWeek = new Date(bucketStart.getTime() + 7 * 24 * 60 * 60 * 1000)
        const startStr = bucketStart.toLocaleDateString('en-US', {
          day: '2-digit', month: 'short', year: 'numeric', timeZone: IST_TZ,
        })
        const endStr = endWeek.toLocaleDateString('en-US', {
          day: '2-digit', month: 'short', year: 'numeric', timeZone: IST_TZ,
        })
        fullLabel = `${startStr} – ${endStr}`
      } else if (bucketType === 'month') {
        fullLabel = bucketStart.toLocaleDateString('en-US', {
          month: 'long', year: 'numeric', timeZone: IST_TZ,
        })
      } else {
        // day
        fullLabel = bucketStart.toLocaleDateString('en-US', {
          weekday: 'long', day: '2-digit', month: 'long', year: 'numeric', timeZone: IST_TZ,
        })
      }
    } catch {
      fullLabel = bucket.label
    }

    // ─── §RESPONSE ─────────────────────────────────────────────────────
    // §CORRECTION-4 + #6: Full traceable hierarchy. Every displayed
    // number has a path back to the underlying records.
    return NextResponse.json({
      // §PERIOD: Server-derived bucket boundaries (NEVER client-provided)
      period: {
        label: bucket.label,
        fullLabel,
        startISO: bucketStart.toISOString(),
        endISO: bucketEnd.toISOString(),
        bucketType,
      },

      // §SUMMARY: Server-authoritative totals (recomputed from REAL records)
      summary: {
        // §NET-REVENUE: tax-exclusive (subtotal - discountAmount)
        netRevenue,
        // §COGS: historical snapshot cost, fallback current cost
        cogs,
        // §GROSS-PROFIT: Net Revenue - COGS
        grossProfit,
        // §OPERATING-EXPENSE: AUTHORITATIVE ONLY (subtype='operating_expense')
        operatingExpense,
        // §LEGACY-OPEX: NULL-subtype + type debit/expense + invoiceId IS NULL
        legacyOpEx,
        // §NET-PROFIT: Gross Profit - authoritative Operating Expense (CAN BE NEGATIVE)
        netProfit,
      },

      // §BREAKDOWN: Traceable records (Correction #6 — full hierarchy)
      breakdown: {
        // §REVENUE-SOURCES: each invoice contributing to netRevenue
        revenueSources,
        // §COGS-SOURCES: each product-line contributing to cogs
        cogsSources,
        // §OPERATING-EXPENSE: authoritative + legacy SEPARATE (never mixed)
        expenseSources: {
          authoritative: authoritativeExpenses,
          legacy: legacyExpenses,
        },
      },

      // §COGS-ACCURACY-DISCLOSURE: same semantics as Reports API
      cogsAccuracy: {
        snapshotItems,
        fallbackItems,
        isApproximate: fallbackItems > 0,
      },
    })
  } catch (e) {
    return apiError(e, 'Failed to load breakdown')
  }
}
